#!/bin/bash

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "🎉 GREAT SUCCESS! Code is on GitHub!"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "✅ GitHub Repository: https://github.com/Aimank009/twap_socket"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "🚂 Now Let's Deploy to Railway!"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Follow these SIMPLE steps:"
echo ""
echo "1️⃣  Open Railway: https://railway.app/new"
echo ""
echo "2️⃣  Click 'Deploy from GitHub repo'"
echo ""
echo "3️⃣  Select: Aimank009/twap_socket"
echo ""
echo "4️⃣  Railway will automatically:"
echo "    ✅ Detect Node.js project"
echo "    ✅ Install dependencies"
echo "    ✅ Start the server"
echo "    ✅ Give you a public URL"
echo ""
echo "5️⃣  Wait 2-3 minutes for deployment"
echo ""
echo "6️⃣  Get your URL from Railway dashboard"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
read -p "Press Enter to open Railway Dashboard..."
open "https://railway.app/new" 2>/dev/null || echo "Please visit: https://railway.app/new"
echo ""
echo "🌐 Railway Dashboard opened in your browser"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "📋 After Deployment is Complete:"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Test your deployment:"
echo ""
read -p "Enter your Railway app URL (without https://): " railway_url

if [ -n "$railway_url" ]; then
    echo ""
    echo "🧪 Testing deployment at: https://$railway_url"
    echo ""
    
    echo "1. Health Check:"
    curl -s "https://$railway_url/" | jq '.' 2>/dev/null || curl -s "https://$railway_url/"
    
    echo ""
    echo "2. Current Price:"
    curl -s "https://$railway_url/api/price" | jq '.' 2>/dev/null || curl -s "https://$railway_url/api/price"
    
    echo ""
    echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    echo "🎉 YOUR ENDPOINTS:"
    echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    echo ""
    echo "🏥 Health Check:"
    echo "   https://$railway_url/"
    echo ""
    echo "💹 Current Price API:"
    echo "   https://$railway_url/api/price"
    echo ""
    echo "📡 Price WebSocket:"
    echo "   wss://$railway_url/ws/prices"
    echo ""
    echo "🎯 Settlement WebSocket:"
    echo "   wss://$railway_url/ws/settlements"
    echo ""
    echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    echo "📝 UPDATE YOUR MERCURY FRONTEND:"
    echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    echo ""
    echo "// In your frontend config:"
    echo "const TWAP_SOCKET_URL = 'wss://$railway_url';"
    echo ""
    echo "// Price feed:"
    echo "const priceWs = new WebSocket('\${TWAP_SOCKET_URL}/ws/prices');"
    echo ""
    echo "// Settlement feed:"
    echo "const settlementWs = new WebSocket('\${TWAP_SOCKET_URL}/ws/settlements');"
    echo ""
    echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    echo ""
    echo "✅ DEPLOYMENT COMPLETE! 🎉"
    echo ""
fi
